### ISSUE TITLE
502 gateway

### ISSUE THREAD

**Issue by jyjohnson** [toniblyx/security_monkey_cloudformation#1]
Hi - I've installed Security Monkey twice and both times I'm getting a red "Error loading resource from API. Error: <HTTP 502:" in the UI. First time I manually copied your script from the UserData section. 2nd after successfully executing the complete cloudformation template.

Any ideas on how I can troubleshoot this?

Thanks.

**Comment by toniblyx** [comment]
Hi Jyjonhson, I'm going to take a look and see what's wrong, thanks for let me know!

**Comment by toniblyx** [comment]
I have seen that is not starting properly due to an permissions issue, working on it...

**Comment by toniblyx** [comment]
Ok, fixed. I have added https://github.com/toniblyx/security_monkey_cloudformation/blob/master/security_monkey_cloudformation-VPC-RDS-SINGLE-SUBNET.template#L589 to make sure securitymonkey.log has proper permissions. I have also improved the Output information that shows CloudFormation after a complete deployment.
