### ISSUE TITLE
List of ubuntu AMI-IDs needs updating

### ISSUE THREAD

**Issue by andrewkrug** [toniblyx/security_monkey_cloudformation#2]
It would seem the marketplace ubuntu images have changed causing this stack_creation to fail.

**Comment by toniblyx** [comment]
Thanks Andrew! I'll update it asap.

**Comment by toniblyx** [comment]
updated with latest Ubumty Trusty (ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-20161205) and added new regions us-east-1 and ca-central-1
